// User Flow Actions
export const CLEAR_DATA = 'CLEAR_DATA'
export const ADD_CAPTION = 'ADD_CAPTION'
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO'
export const SELECTED_PHOTO = 'SELECTED_PHOTO'
export const CLEAN_REDUCERS = 'CLEAN_REDUCERS'


// Results Actions
export const LABEL_DATA = 'LABEL_DATA'
export const RESULT_URL = 'RESULT_URL'
export const GET_LABEL_ID = 'GET_LABEL_ID'
export const POST_LABEL_ID = 'POST_LABEL_ID'
export const SEND_SERIALIZED_DATA = 'SEND_SERIALIZED_DATA'
export const STORE_PARSED_DATA = 'STORE_PARSED_DATA'
export const CLEAR_FIREBASE_DATA = 'CLEAR_FIREBASE_DATA'
export const INITIALIZE_FIREBASE_DATA = 'INITIALIZE_FIREBASE_DATA'
export const INGREDIENT_FIREBASE_DATA = 'INGREDIENT_FIREBASE_DATA'
export const LAZY_FETCH_FIREBASE = 'LAZY_FETCH_FIREBASE'
export const LAZY_LOAD_FIREBASE = 'LAZY_LOAD_FIREBASE'
export const RESET_LAZY_LOAD_STATUS = 'RESET_LAZY_LOAD_STATUS'
export const SEARCH_INGREDIENT = 'SEARCH_INGREDIENT'
export const SEARCH_RESULT = 'SEARCH_RESULT'
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const RESET_SEARCH_FLAG = 'RESET_SEARCH_FLAG'
export const SELECTED_TAGS = 'SELECTED_TAGS'
export const UNUSED_TAGS = 'UNUSED_TAGS'


// Model Actions
export const NM_RESET = 'NM_RESET'
export const NM_SETUP = 'NM_SETUP'
export const NM_ADD_INGREDIENT = 'NM_ADD_INGREDIENT'
export const NM_REM_INGREDIENT = 'NM_REM_INGREDIENT'
export const NM_SET_SERVINGS = 'NM_SET_SERVINGS'
export const NM_SCALE_INGREDIENT = 'NM_SCALE_INGREDIENT'
export const IM_ADD_CONTROL_MODEL = 'IM_ADD_CONTROL_MODEL'
export const IM_SET_SLIDER_VALUE = 'IM_SET_SLIDER_VALUE'
export const IM_SET_EDIT_BOX_VALUE = 'IM_SET_EDIT_BOX_VALUE'
export const IM_SET_DROPDOWN_MATCH_VALUE = 'IM_SET_DROPDOWN_MATCH_VALUE'
export const IM_SET_DROPDOWN_UNITS = 'IM_SET_DROPDOWN_UNITS'
export const IM_SET_DROPDOWN_UNITS_VALUE = 'IM_SET_DROPDOWN_UNITS_VALUE'
export const IM_REM_INGREDIENT_TAG = 'IM_REM_INGREDIENT_TAG'
export const MISSING_INGREDIENT = 'MISSING_INGREDIENT'
export const GET_MORE_DATA = 'GET_MORE_DATA'
export const RESET_APPEND_DATA = 'RESET_APPEND_DATA'
export const REMOVE_ELLIPSES = 'REMOVE_ELLIPSES'


// ServingsController Actions
export const SC_STORE_VALUES = 'SC_STORE_VALUES'
export const COMPLETE_DROPDOWN_CHANGE = 'COMPLETE_DROPDOWN_CHANGE'


// Email Actions
export const INIT_EMAIL_FLOW = 'INIT_EMAIL_FLOW'
export const GET_EMAIL_DATA = 'GET_EMAIL_DATA'


// FDA Actions
export const SET_FDA_RESULTS = 'SET_FDA_RESULTS'