// User Flow Actions
export const CLEAR_DATA = 'CLEAR_DATA'
export const SAVE_TO_CLOUD = 'SAVE_TO_CLOUD'
export const SELECTED_PHOTO = 'SELECTED_PHOTO'
export const GET_MORE_DATA = 'GET_MORE_DATA'
export const GET_COMMERCIAL_DATA = 'GET_COMMERCIAL_DATA'
export const SET_TITLE = 'SET_TITLE'

// Results Actions
export const LABEL_DATA = 'LABEL_DATA'
export const RESULT_URL = 'RESULT_URL'
export const GET_LABEL_ID = 'GET_LABEL_ID'
export const POST_LABEL_ID = 'POST_LABEL_ID'
export const SEND_SERIALIZED_DATA = 'SEND_SERIALIZED_DATA'
export const STORE_PARSED_DATA = 'STORE_PARSED_DATA'
export const SET_PARSED_DATA = 'SET_PARSED_DATA'
export const CLEAR_FIREBASE_DATA = 'CLEAR_FIREBASE_DATA'
export const INITIALIZE_FIREBASE_DATA = 'INITIALIZE_FIREBASE_DATA'
export const INGREDIENT_FIREBASE_DATA = 'INGREDIENT_FIREBASE_DATA'
export const LAZY_FETCH_FIREBASE = 'LAZY_FETCH_FIREBASE'
export const LAZY_LOAD_FIREBASE = 'LAZY_LOAD_FIREBASE'
export const DELETED_TAGS = 'DELETED_TAGS'
export const UNUSED_TAGS = 'UNUSED_TAGS'
export const SEND_USER_GENERATED_DATA = 'SEND_USER_GENERATED_DATA'


// Model Actions
export const MODEL_RESET = 'MODEL_RESET'
export const NM_ADD_INGREDIENT = 'NM_ADD_INGREDIENT'
export const NM_REM_INGREDIENT = 'NM_REM_INGREDIENT'
export const NM_SET_SERVINGS = 'NM_SET_SERVINGS'
export const NM_SCALE_INGREDIENT = 'NM_SCALE_INGREDIENT'
export const NM_SET_LABEL_TYPE = 'NM_SET_LABEL_TYPE'
export const IM_ADD_CONTROL_MODEL = 'IM_ADD_CONTROL_MODEL'
export const IM_UPDATE_MODEL = 'IM_UPDATE_MODEL'
export const IM_REM_INGREDIENT_TAG = 'IM_REM_INGREDIENT_TAG'
export const GET_FIREBASE_DATA = 'GET_FIREBASE_DATA'


// ServingsController Actions
export const SC_STORE_MODEL = 'SC_STORE_MODEL'
export const COMPLETE_DROPDOWN_CHANGE = 'COMPLETE_DROPDOWN_CHANGE'


// Email Actions
export const INIT_EMAIL_FLOW = 'INIT_EMAIL_FLOW'
export const GET_EMAIL_DATA = 'GET_EMAIL_DATA'


// Search Actions
export const ADD_SEARCH_SELECTION = 'ADD_SEARCH_SELECTION'
export const CLOSE_SEARCH_MODAL = 'CLOSE_SEARCH_MODAL'
export const SET_FDA_RESULTS = 'SET_FDA_RESULTS'
export const PARSE_SEARCH_DATA = 'PARSE_SEARCH_DATA'
export const PARSE_SEARCH_FDA_DATA = 'PARSE_SEARCH_FDA_DATA'
export const NUT_SEARCH_RESULTS = 'NUT_SEARCH_RESULTS'
export const SEARCH_INGREDIENT_COMMERCIAL = 'SEARCH_INGREDIENT_COMMERCIAL'
export const SUPER_SEARCH_RESULTS = 'SUPER_SEARCH_RESULTS'
export const INITIALIZE_RECIPE_FLOW = 'INITIALIZE_RECIPE_FLOW'
export const INITIALIZE_SEARCH_FLOW = 'INITIALIZE_SEARCH_FLOW'
export const SEARCH_TIMED_OUT = 'SEARCH_TIMED_OUT'
export const UPDATE_MATCH_RESULTS_MODEL = 'UPDATE_MATCH_RESULTS_MODEL'
export const UPDATE_MATCH_RESULTS_SEARCH_INDEX = 'UPDATE_MATCH_RESULTS_SEARCH_INDEX'
